### ISSUE TITLE
"web-robot.py" not RUN !

### ISSUE THREAD

**Issue by idreamsi** [penguintutor/web-robot#1]
hi
When I run the "web-robot.py" following error is displayed:
![web-robot](https://cloud.githubusercontent.com/assets/8011806/3422625/76a925ec-ff52-11e3-92fd-d3cb2a6631c3.jpg)

Where is the problem?

**Comment by penguintutor** [comment]
I will look into the issue over the next few days. I am in the process of testing putting the code onto another robot chassis to see what the issue may be.

**Comment by idreamsi** [comment]
thanks.
I am waiting for the answer.

**Comment by penguintutor** [comment]
Sorry for the delay.

I've been unable to recreate the error that you are experiencing. 

Please check that you have the appropriate bottle.py file in the same directory as the web-robot.py file. If that directory is not /home/pi/robot then you may need to update the python code to reflect the new directory name.

This is still very early code, I hope to develop this further in the future and will provide better documentation on how to install and configure the code.

**Comment by idreamsi** [comment]
The problem was solved.
thank you.
